### ISSUE TITLE
make errror

### ISSUE THREAD

**Issue by Nagatejapallapu** [trmckay/riscv-kernel-convolution#1]
~/riscv-kernel-convolution$ make all
mkdir -p build
riscv32-unknown-elf-gcc  -o build/program.elf otter/init.s otter/main.s otter/draw.c otter/interrupt.c otter/processing.c -T link.ld -O3 -march=rv32i -mabi=ilp32 -g 
make: riscv32-unknown-elf-gcc: Command not found
Makefile:59: recipe for target 'build/program.elf' failed
make: *** [build/program.elf] Error 127

**Comment by trmckay** [comment]
You need a [riscv toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain), not system gcc to build.
