### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Nagatejapallapu** [trmckay/riscv-kernel-convolution#2]
~/riscv-kernel-convolution$ sudo make all
mkdir -p build
riscv32-unknown-elf-gcc  -o build/program.elf otter/init.s otter/main.s otter/draw.c otter/interrupt.c otter/processing.c -T link.ld -O3 -march=rv32i -mabi=ilp32 -g 
make: riscv32-unknown-elf-gcc: Command not found
Makefile:59: recipe for target 'build/program.elf' failed
make: *** [build/program.elf] Error 127

**Comment by trmckay** [comment]
Again, you don't have a toolchain.
https://github.com/trmckay/riscv-kernel-convolution/issues/1
